name: Raspberry Pi Tests

on:
  push:
    branches:
      - main
      - dev-zigbee-address-assignment 

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run setup script with CI flag
      run: |
        chmod +x setup.sh
        ./setup.sh --ci

    - name: Run Zigbee integration tests
      run: |
        source venv/bin/activate
        ./tests/integration_test_zigbee.sh

    - name: Run sensor error tests
      run: |
        source venv/bin/activate
        ./tests/test_sensor_errors.sh

    - name: Run controller tests
      run: |
        source venv/bin/activate
        ./tests/test_controllers.sh

